[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -jar target/quarkus-app/quarkus-run.jar'

[variables]
MAVEN_OPTS = '-Xmx512m'
