[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${PORT:-8080} -jar target/quarkus-app/quarkus-run.jar'

[variables]
MAVEN_OPTS = '-Xmx512m'
